// -------------------------------------------------------------
// 
// File Name: C:\Users\marcel.roth\Desktop\Support Matlab\FIR-code\hdlsrc\FIR_filter\FIR_filter.v
// Created: 2016-11-04 10:27:25
// 
// Generated by MATLAB 9.1 and HDL Coder 3.9
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.2
// Target subsystem base rate: 0.2
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.2
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out                           ce_out        0.2
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FIR_filter
// Source Path: FIR_filter
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FIR_filter
          (
           clk,
           reset,
           clk_enable,
           In,
           ce_out,
           Out
          );



  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [13:0] In;  // sfix14
  output  ce_out;
  output  signed [13:0] Out;  // sfix14

  wire signed [13:0] filter_out1;  // sfix14


  filter   u_filter   (.clk(clk),
                       .reset(reset),
                       .enb(clk_enable),
                       .filter_in(In),  // sfix14
                       .filter_out(filter_out1)  // sfix14
                       );

  assign Out = filter_out1;

  assign ce_out = clk_enable;

endmodule  // FIR_filter

